export const CONNECTION_REQUEST = 'CONNECTION REQUEST';
export const CONNECTION_SUCCESS = 'CONNECTION SUCCESS';
export const CONNECTION_FAILED = 'CONNECTION FAILED';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
