export const CONNECTION_REQUEST = 'CONNECTION REQUEST';
export const CONNECTION_SUCCESS = 'CONNECTION SUCCESS';
export const CONNECTION_FAILED = 'CONNECTION FAILED';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const CHECK_METADATA_REQUEST = 'CHECK_METADATA_REQUEST';
export const CHECK_METADATA_SUCCESS = 'CHECK_METADATA_SUCCESS';
export const CHECK_METADATA_FAILED = 'CHECK_METADATA_FAILED';
