export const CONNECTION_REQUEST = 'CONNECTION REQUEST';
export const CONNECTION_SUCCESS = 'CONNECTION SUCCESS';
export const CONNECTION_FAILED = 'CONNECTION FAILED';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const CHECK_LAMP_REQUEST = 'CHECK_LAMP_REQUEST';
export const CHECK_LAMP_SUCCESS = 'CHECK_LAMP_SUCCESS';
export const CHECK_LAMP_FAILED = 'CHECK_LAMP_FAILED';
