const {
  attributes,
  backgrounds,
  bases,
  glasses,
  glassColorIndexes,
  lavaColorIndexes,
  rarities,
  overlays,
} = require('../../../src/images/LavaLampGenerator/');

const lavaLampTraits = [
  {
    attribute: attributes.lavalien,
    background: backgrounds.stars,
    base: bases.rocket,
    glass: glasses.normal,
    glassColor: glassColorIndexes.yellow,
    lava1: lavaColorIndexes.blue,
    lava2: lavaColorIndexes.green,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.yellow,
    overlay: overlays.none,
    rarity: rarities.og,
  },
  {
    attribute: attributes.none,
    background: backgrounds.strawberry,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.red,
    lava1: lavaColorIndexes.green,
    lava2: lavaColorIndexes.red,
    lava3: lavaColorIndexes.purple,
    lava4: lavaColorIndexes.white,
    overlay: overlays.yinYang,
    rarity: rarities.ruby,
  },
  {
    attribute: attributes.none,
    background: backgrounds.sky,
    base: bases.standard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.blue,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.blue,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.blue,
    overlay: overlays.none,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.none,
    background: backgrounds.purple,
    base: bases.bong,
    glass: glasses.normal,
    glassColor: glassColorIndexes.purple,
    lava1: lavaColorIndexes.pink,
    lava2: lavaColorIndexes.yellow,
    lava3: lavaColorIndexes.blue,
    lava4: lavaColorIndexes.green,
    overlay: overlays.leaves,
    rarity: rarities.og,
  },
  {
    attribute: attributes.none,
    background: backgrounds.lightStrawberry,
    base: bases.kitty,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.red,
    lava2: lavaColorIndexes.green,
    lava3: lavaColorIndexes.orange,
    lava4: lavaColorIndexes.blue,
    overlay: overlays.none,
    rarity: rarities.rainbow,
  },
  {
    attribute: attributes.halo,
    background: backgrounds.raspberry,
    base: bases.standard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.black,
    lava1: lavaColorIndexes.purple,
    lava2: lavaColorIndexes.lightBlue,
    lava3: lavaColorIndexes.green,
    lava4: lavaColorIndexes.pink,
    overlay: overlays.swirls,
    rarity: rarities.og,
  },
  {
    attribute: attributes.kitty,
    background: backgrounds.lightBlueberry,
    base: bases.pumpkin,
    glass: glasses.normal,
    glassColor: glassColorIndexes.blue,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.green,
    lava4: lavaColorIndexes.yellow,
    overlay: overlays.peace,
    rarity: rarities.og,
  },
  {
    attribute: attributes.halo,
    background: backgrounds.blueberry,
    base: bases.standard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.black,
    lava1: lavaColorIndexes.red,
    lava2: lavaColorIndexes.yellow,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.green,
    overlay: overlays.peace,
    rarity: rarities.rainbow,
  },
  {
    attribute: attributes.kitty,
    background: backgrounds.purple,
    base: bases.witch,
    glass: glasses.normal,
    glassColor: glassColorIndexes.blue,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.green,
    lava4: lavaColorIndexes.yellow,
    overlay: overlays.yinYang,
    rarity: rarities.og,
  },
  {
    attribute: attributes.none,
    background: backgrounds.strawberry,
    base: bases.wizard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.white,
    lava2: lavaColorIndexes.green,
    lava3: lavaColorIndexes.blue,
    lava4: lavaColorIndexes.red,
    overlay: overlays.leaves,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.none,
    background: backgrounds.lightRaspberry,
    base: bases.pumpkin,
    glass: glasses.normal,
    glassColor: glassColorIndexes.black,
    lava1: lavaColorIndexes.green,
    lava2: lavaColorIndexes.red,
    lava3: lavaColorIndexes.orange,
    lava4: lavaColorIndexes.pink,
    overlay: overlays.swirls,
    rarity: rarities.og,
  },
  {
    attribute: attributes.none,
    background: backgrounds.sky,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.yellow,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.white,
    lava3: lavaColorIndexes.green,
    lava4: lavaColorIndexes.blue,
    overlay: overlays.none,
    rarity: rarities.og,
  },
  {
    attribute: attributes.halo,
    background: backgrounds.black,
    base: bases.standard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.yellow,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.lightBlue,
    overlay: overlays.ethereum,
    rarity: rarities.gold,
  },
  {
    attribute: attributes.none,
    background: backgrounds.raspberry,
    base: bases.wizard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.yellow,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.red,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.pink,
    overlay: overlays.bitcoin,
    rarity: rarities.gold,
  },
  {
    attribute: attributes.kitty,
    background: backgrounds.raspberry,
    base: bases.wizard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.purple,
    lava3: lavaColorIndexes.pink,
    lava4: lavaColorIndexes.green,
    overlay: overlays.swirls,
    rarity: rarities.og,
  },
  {
    attribute: attributes.none,
    background: backgrounds.stars,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.orange,
    lava1: lavaColorIndexes.blue,
    lava2: lavaColorIndexes.yellow,
    lava3: lavaColorIndexes.none,
    lava4: lavaColorIndexes.red,
    overlay: overlays.none,
    rarity: rarities.gold,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.black,
    base: bases.bong,
    glass: glasses.normal,
    glassColor: glassColorIndexes.black,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.emerald,
  },
  {
    attribute: attributes.kitty,
    background: backgrounds.lightBlueberry,
    base: bases.kitty,
    glass: glasses.normal,
    glassColor: glassColorIndexes.yellow,
    lava1: lavaColorIndexes.red,
    lava2: lavaColorIndexes.purple,
    lava3: lavaColorIndexes.pink,
    lava4: lavaColorIndexes.white,
    overlay: overlays.lavaCeption,
    rarity: rarities.emerald,
  },
  {
    attribute: attributes.none,
    background: backgrounds.blueberry,
    base: bases.pumpkin,
    glass: glasses.normal,
    glassColor: glassColorIndexes.pink,
    lava1: lavaColorIndexes.red,
    lava2: lavaColorIndexes.lightBlue,
    lava3: lavaColorIndexes.yellow,
    lava4: lavaColorIndexes.orange,
    overlay: overlays.yinYang,
    rarity: rarities.rainbow,
  },
  {
    attribute: attributes.halo,
    background: backgrounds.sky,
    base: bases.rocket,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.blue,
    lava2: lavaColorIndexes.green,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.yellow,
    overlay: overlays.none,
    rarity: rarities.ruby,
  },
  {
    attribute: attributes.none,
    background: backgrounds.strawberry,
    base: bases.bong,
    glass: glasses.normal,
    glassColor: glassColorIndexes.yellow,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.swirls,
    rarity: rarities.gold,
  },
  {
    attribute: attributes.none,
    background: backgrounds.stars,
    base: bases.standard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.purple,
    lava2: lavaColorIndexes.lightBlue,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.pink,
    overlay: overlays.ethereum,
    rarity: rarities.emerald,
  },
  {
    attribute: attributes.none,
    background: backgrounds.raspberry,
    base: bases.witch,
    glass: glasses.normal,
    glassColor: glassColorIndexes.blue,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.green,
    lava4: lavaColorIndexes.red,
    overlay: overlays.peace,
    rarity: rarities.rainbow,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.lightStrawberry,
    base: bases.kitty,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.green,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.pink,
    overlay: overlays.none,
    rarity: rarities.og,
  },
  {
    attribute: attributes.none,
    background: backgrounds.lightRaspberry,
    base: bases.standard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.purple,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.yinYang,
    rarity: rarities.ruby,
  },
  {
    attribute: attributes.kitty,
    background: backgrounds.lightBlueberry,
    base: bases.witch,
    glass: glasses.normal,
    glassColor: glassColorIndexes.blue,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.green,
    lava4: lavaColorIndexes.yellow,
    overlay: overlays.yinYang,
    rarity: rarities.emerald,
  },
  {
    attribute: attributes.none,
    background: backgrounds.blueberry,
    base: bases.bong,
    glass: glasses.normal,
    glassColor: glassColorIndexes.yellow,
    lava1: lavaColorIndexes.pink,
    lava2: lavaColorIndexes.blue,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.yellow,
    overlay: overlays.swirls,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.none,
    background: backgrounds.black,
    base: bases.wizard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.red,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.yellow,
    lava4: lavaColorIndexes.red,
    overlay: overlays.leaves,
    rarity: rarities.rainbow,
  },
];

export default lavaLampTraits;
