const {
  attributes,
  backgrounds,
  bases,
  glasses,
  glassColorIndexes,
  lavaColorIndexes,
  rarities,
  overlays,
  swagger,
} = require('../../../src/images/LavaLampGenerator/');

const lavaLampTraits = [
  {
    attribute: attributes.lavalien,
    background: backgrounds.star,
    base: bases.rocket,
    glass: glasses.normal,
    glassColor: glassColorIndexes.amber,
    lava1: lavaColorIndexes.blue,
    lava2: lavaColorIndexes.green,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.yellow,
    overlay: overlays.none,
    rarity: rarities.og,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.magma,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.molten,
    lava1: lavaColorIndexes.green,
    lava2: lavaColorIndexes.red,
    lava3: lavaColorIndexes.purple,
    lava4: lavaColorIndexes.white,
    overlay: overlays.yinYang,
    rarity: rarities.ruby,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.sky,
    base: bases.standard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.cerulean,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.blue,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.blue,
    overlay: overlays.none,
    rarity: rarities.diamond,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.royal,
    base: bases.bong,
    glass: glasses.normal,
    glassColor: glassColorIndexes.purpleHaze,
    lava1: lavaColorIndexes.pink,
    lava2: lavaColorIndexes.yellow,
    lava3: lavaColorIndexes.blue,
    lava4: lavaColorIndexes.green,
    overlay: overlays.weed,
    rarity: rarities.og,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.peach,
    base: bases.cat,
    glass: glasses.normal,
    glassColor: glassColorIndexes.pearl,
    lava1: lavaColorIndexes.red,
    lava2: lavaColorIndexes.green,
    lava3: lavaColorIndexes.orange,
    lava4: lavaColorIndexes.blue,
    overlay: overlays.none,
    rarity: rarities.rainbow,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.halo,
    background: backgrounds.plum,
    base: bases.standard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.carbon,
    lava1: lavaColorIndexes.purple,
    lava2: lavaColorIndexes.lightBlue,
    lava3: lavaColorIndexes.green,
    lava4: lavaColorIndexes.pink,
    overlay: overlays.swirl,
    rarity: rarities.og,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.lavaKitty,
    background: backgrounds.cottonCandy,
    base: bases.pumpkin,
    glass: glasses.normal,
    glassColor: glassColorIndexes.cerulean,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.green,
    lava4: lavaColorIndexes.yellow,
    overlay: overlays.peace,
    rarity: rarities.og,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.halo,
    background: backgrounds.sapphire,
    base: bases.standard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.carbon,
    lava1: lavaColorIndexes.red,
    lava2: lavaColorIndexes.yellow,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.green,
    overlay: overlays.peace,
    rarity: rarities.rainbow,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.lavaKitty,
    background: backgrounds.royal,
    base: bases.witch,
    glass: glasses.normal,
    glassColor: glassColorIndexes.cerulean,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.green,
    lava4: lavaColorIndexes.yellow,
    overlay: overlays.yinYang,
    rarity: rarities.og,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.magma,
    base: bases.wizard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.pearl,
    lava1: lavaColorIndexes.white,
    lava2: lavaColorIndexes.green,
    lava3: lavaColorIndexes.blue,
    lava4: lavaColorIndexes.red,
    overlay: overlays.weed,
    rarity: rarities.diamond,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.peach,
    base: bases.pumpkin,
    glass: glasses.normal,
    glassColor: glassColorIndexes.carbon,
    lava1: lavaColorIndexes.green,
    lava2: lavaColorIndexes.red,
    lava3: lavaColorIndexes.orange,
    lava4: lavaColorIndexes.pink,
    overlay: overlays.swirl,
    rarity: rarities.og,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.sky,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.amber,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.white,
    lava3: lavaColorIndexes.green,
    lava4: lavaColorIndexes.blue,
    overlay: overlays.none,
    rarity: rarities.og,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.halo,
    background: backgrounds.ash,
    base: bases.standard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.amber,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.lightBlue,
    overlay: overlays.ethereum,
    rarity: rarities.gold,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.plum,
    base: bases.wizard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.amber,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.red,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.pink,
    overlay: overlays.bitcoin,
    rarity: rarities.gold,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.lavaKitty,
    background: backgrounds.plum,
    base: bases.wizard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.pearl,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.purple,
    lava3: lavaColorIndexes.pink,
    lava4: lavaColorIndexes.green,
    overlay: overlays.swirl,
    rarity: rarities.og,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.star,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.tiger,
    lava1: lavaColorIndexes.blue,
    lava2: lavaColorIndexes.yellow,
    lava3: lavaColorIndexes.none,
    lava4: lavaColorIndexes.red,
    overlay: overlays.none,
    rarity: rarities.gold,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.ash,
    base: bases.bong,
    glass: glasses.normal,
    glassColor: glassColorIndexes.carbon,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.emerald,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.lavaKitty,
    background: backgrounds.cottonCandy,
    base: bases.cat,
    glass: glasses.normal,
    glassColor: glassColorIndexes.amber,
    lava1: lavaColorIndexes.red,
    lava2: lavaColorIndexes.purple,
    lava3: lavaColorIndexes.pink,
    lava4: lavaColorIndexes.white,
    overlay: overlays.lavaCeption,
    rarity: rarities.emerald,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.sapphire,
    base: bases.pumpkin,
    glass: glasses.normal,
    glassColor: glassColorIndexes.blossom,
    lava1: lavaColorIndexes.red,
    lava2: lavaColorIndexes.lightBlue,
    lava3: lavaColorIndexes.yellow,
    lava4: lavaColorIndexes.orange,
    overlay: overlays.yinYang,
    rarity: rarities.rainbow,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.halo,
    background: backgrounds.sky,
    base: bases.rocket,
    glass: glasses.normal,
    glassColor: glassColorIndexes.pearl,
    lava1: lavaColorIndexes.blue,
    lava2: lavaColorIndexes.green,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.yellow,
    overlay: overlays.none,
    rarity: rarities.ruby,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.magma,
    base: bases.bong,
    glass: glasses.normal,
    glassColor: glassColorIndexes.amber,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.swirl,
    rarity: rarities.gold,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.star,
    base: bases.standard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.pearl,
    lava1: lavaColorIndexes.purple,
    lava2: lavaColorIndexes.lightBlue,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.pink,
    overlay: overlays.ethereum,
    rarity: rarities.emerald,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.plum,
    base: bases.witch,
    glass: glasses.normal,
    glassColor: glassColorIndexes.cerulean,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.green,
    lava4: lavaColorIndexes.red,
    overlay: overlays.peace,
    rarity: rarities.rainbow,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.bubbleGum,
    base: bases.cat,
    glass: glasses.normal,
    glassColor: glassColorIndexes.pearl,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.green,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.pink,
    overlay: overlays.none,
    rarity: rarities.og,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.peach,
    base: bases.standard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.purpleHaze,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.white,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.yinYang,
    rarity: rarities.ruby,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.lavaKitty,
    background: backgrounds.cottonCandy,
    base: bases.witch,
    glass: glasses.normal,
    glassColor: glassColorIndexes.cerulean,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.green,
    lava4: lavaColorIndexes.yellow,
    overlay: overlays.yinYang,
    rarity: rarities.emerald,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.sapphire,
    base: bases.bong,
    glass: glasses.normal,
    glassColor: glassColorIndexes.amber,
    lava1: lavaColorIndexes.pink,
    lava2: lavaColorIndexes.blue,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.yellow,
    overlay: overlays.swirl,
    rarity: rarities.diamond,
    swag: swagger.inactive,
  },
  {
    attribute: attributes.none,
    background: backgrounds.ash,
    base: bases.wizard,
    glass: glasses.normal,
    glassColor: glassColorIndexes.molten,
    lava1: lavaColorIndexes.lightBlue,
    lava2: lavaColorIndexes.orange,
    lava3: lavaColorIndexes.yellow,
    lava4: lavaColorIndexes.red,
    overlay: overlays.weed,
    rarity: rarities.rainbow,
    swag: swagger.inactive,
  },
];

export default lavaLampTraits;
