const {
  attributes,
  backgrounds,
  bases,
  glasses,
  glassColorIndexes,
  lavaColorIndexes,
  rarities,
  overlays,
} = require('../../../src/images/LavaLampGenerator/');

const lavaLampTraits = [
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
  {
    attribute: attributes.lavalien,
    background: backgrounds.purple,
    base: bases.alien,
    glass: glasses.normal,
    glassColor: glassColorIndexes.white,
    lava1: lavaColorIndexes.orange,
    lava2: lavaColorIndexes.pink,
    lava3: lavaColorIndexes.lightBlue,
    lava4: lavaColorIndexes.purple,
    overlay: overlays.smoke,
    rarity: rarities.diamond,
  },
];

export default lavaLampTraits;
