const {
  generateLavaLamp,
  generateRandomLavaLamp,
  generateNRandomLavaLamps,
  BuyMoreLavaLamps,
} = require('./GenerateLavaLampSVGs');
const {generateMetadata} = require('./GenerateLavaLampMetadata');
const {
  attributes,
  backgrounds,
  bases,
  glasses,
  glassColors,
  glassColorIndexes,
  lavaColors,
  lavaColorIndexes,
  rarities,
  overlays,
  swagger,
  attributeMetadata,
  backgroundMetadata,
  baseMetadata,
  glassMetadata,
  glassColorMetadata,
  lavaColorMetadata,
  rarityMetadata,
  overlayMetadata,
  swagMetadata,
} = require('./Traits');

module.exports = {
  generateLavaLamp,
  generateMetadata,
  generateRandomLavaLamp,
  generateNRandomLavaLamps,
  BuyMoreLavaLamps,
  attributes,
  backgrounds,
  bases,
  glasses,
  glassColors,
  glassColorIndexes,
  lavaColors,
  lavaColorIndexes,
  rarities,
  overlays,
  swagger,
  attributeMetadata,
  backgroundMetadata,
  baseMetadata,
  glassMetadata,
  glassColorMetadata,
  lavaColorMetadata,
  rarityMetadata,
  overlayMetadata,
  swagMetadata,
};
